language: java
jdk: oraclejdk8
dist: trusty

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      script:
        - export SDK_NAME="java4"
        - export SDK_VERSION=$(cut -d'v' -f2 <<<"$TRAVIS_TAG")
        - echo $TRAVIS_TAG
        - echo $RELEASE_CANDIDATE
        - if [[ $TRAVIS_TAG =~ ^RELEASE_CANDIDATE ]]; then
          git remote set-url origin https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG};
          mvn versions:set -DnewVersion=$SDK_VERSION;
          mvn versions:commit;
          git add */pom.xml pom.xml;
          git commit -m 'update pom version';
          git push origin HEAD:$RELEASE_BRANCH;
          fi


    - stage: deploy
      script:
        - echo "Deploy"
        - sh set_tags.sh